### ISSUE TITLE
The plugin does not support import capability

### ISSUE THREAD

**Issue by dkossako** [nm-l2tp/NetworkManager-l2tp#146]
Hello, starting with Ubuntu 20.20 and Linux Mint 20 there is no more possible to import configurations due to error:

> The plugin does not support import capability

Packages versions:
> daniel@daniel-pc:/etc$ dpkg -l | grep l2tp
> ii  network-manager-l2tp                          1.2.16-1                              amd64        network management framework (L2TP plugin core)
> ii  network-manager-l2tp-gnome                    1.2.16-1                              amd64        network management framework (L2TP plugin GNOME GUI)
> ii  xl2tpd                                        1.3.12-1.1                            amd64        layer 2 tunneling protocol implementation

**Comment by dkosovic** [comment]
That is by design, the import and export code was old and unmaintained, so I removed it. It needs a lot of conditionals to be added to mimic what the editor and backend nm-l2tp-servce are doing. It might be added back one day.

You can copy the corresponding VPN connection configuration from `/etc/NetworkManager/system-connections/`

Once you have copied it across to the same location on the other computer, you can inform NetworkManager to look for the new connection configuration(s) by issuing:
```
sudo nmcli con reload
```
