### ISSUE TITLE
No left margin (or padding) for all controls and settings  on PPP settings window...

### ISSUE THREAD

**Issue by dasnoopy** [nm-l2tp/NetworkManager-l2tp#197]
- Gnome 43.1  on Arch linux 64 bit
- gtk4  4.8.2
- networkmanager-l2tp vers.  1.20.6

I think that left margin (or padding) in the PPP options windows is not correct...

[Screencast from 2022-11-15 19-21-30.webm](https://user-images.githubusercontent.com/296922/202002184-4d4e38e5-1e54-4cdc-81f2-4d9ebc165c93.webm)

here how it should be ( https://github.com/nm-l2tp/NetworkManager-l2tp/wiki/Screenshots )  :-)

Regards
Andrea

**Comment by dkosovic** [comment]
I think it is related to commit# https://github.com/nm-l2tp/NetworkManager-l2tp/commit/386f310fa11ed918ff3f2156f101297cec933140  which removed a `border-width` (aka `border_width`) property that was set to 5, because the `border-width` property is no longer supported by GTK 4.

Not sure yet what a fix will be.
